[package]
name = "gsim-rs"
version = "1.0.0"
edition = "2024"
description = "A G-Code simulator written in Rust."
license = "MIT OR Apache-2.0"
repository = "https://github.com/navrajkalsi/gsim-rs"
keywords = ["parsing", "simulation", "tui", "gcode", "wgpu", "ratatui"]
categories = ["command-line-utilities", "rendering", "simulation"]
exclude = ["gcodes", "media"]

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.0", features = ["derive"] }
pollster = "0.4.0"
ratatui = "0.30.0"
wgpu = "29.0.1"
winit = "0.30.13"
bytemuck = { version = "1.24", features = [ "derive" ] }
env_logger = "0.11.10"
log = "0.4.30"
thiserror = "2.0.18"
